server:
  port: 8081
rpc:
  name: ZRPC
  version: 1.0
  server-host: localhost
  server-port: 8090
  cors: client
  serializer-type: fastjson
  loadbalancer-type: round-robin
  registry:
    type: zookeeper
    host: 122.51.24.81
    port: 2181
    timeout: 10000
